### ISSUE TITLE
Epic A1) Development of forms for all sections of RD CDM

### ISSUE THREAD

**Issue by aslgraefe** [BIH-CEI/rarelink#15]
- [x] #18
- [x] define all elements in field annotations
- [x] include comments and instructions if necessary
- [x] consider ActionTags and BranchingLogic
- [x] #21

**Comment by aslgraefe** [comment]
done, but make rules for shortening , see other issue

**Comment by aslgraefe** [comment]
https://github.com/BIH-CEI/RareLink/issues/17
